<a href="https://colab.research.google.com/github/jeffersonquispe/Tuto_Pytorch/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

In [3]:
a=np.random.rand(4,3)
a

array([[0.05142034, 0.48117328, 0.29415406],
       [0.3803283 , 0.33365963, 0.64855945],
       [0.85443196, 0.79218405, 0.96016012],
       [0.61336344, 0.32099055, 0.94432077]])

In [7]:
b=torch.from_numpy(a)
b

tensor([[0.0514, 0.4812, 0.2942],
        [0.3803, 0.3337, 0.6486],
        [0.8544, 0.7922, 0.9602],
        [0.6134, 0.3210, 0.9443]], dtype=torch.float64)

In [8]:
b.numpy

<function Tensor.numpy>

In [9]:
b.mul_(2)

tensor([[0.1028, 0.9623, 0.5883],
        [0.7607, 0.6673, 1.2971],
        [1.7089, 1.5844, 1.9203],
        [1.2267, 0.6420, 1.8886]], dtype=torch.float64)