<a href="https://colab.research.google.com/github/jeffersonquispe/Tuto_Pytorch/blob/master/SingleLayersNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
  
  """
    Sigmond activation function:
    x:torch.Tensor
  """
  return 1/(1+torch.exp(-x))

In [0]:
###Generate some data
torch.manual_seed(7)# set the random seed
features =torch.randn((1,3))#5 random normal varaibles
weights = torch.randn_like(features)#pesos de la data, randon variables again
bias=torch.randn((1,1))# and a true bias term
n_inputs=features.shape[1]
n_hidden=2
n_output=1

W1=torch.randn(n_input, n_hidden)
W2=torch.randn(n_hidden,n_output)

B1=torch.randn(1,n_hidden)
B2=torch.randn(1,n_output)

In [18]:
sum = torch.sum(torch.mm(features, weights.view(3, 1)))+ bias
print(sum)
print(features)
print(bias)
print(n_inputs)

tensor([[0.2899]])
tensor([[-0.1468,  0.7861,  0.9468]])
tensor([[-0.3556]])
3


In [0]:
y=activation(torch.sum(torch.mm(torch.sum(torch.mm(features,W1.view(3,1)))+B1,W2.view(3,1))+B2)

SyntaxError: ignored

In [19]:
h=activation(torch.mm(features, W1)+B1)
output=activation(torch.mm(h,W2)+B2)
print(output)

tensor([[0.8371]])
